version: '3'
services:

  php:
    build: _docker/php
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - web
    ports:
    - ${PHP_HTTP_PORT}:80
    - ${PHP_HTTPS_PORT}:443
    restart: always

networks:
  web:
    driver: bridge
